#%RAML 1.0
title: Drinks Services
description: raml doc
version: ${project.version}
mediaType: application/json
documentation: 
  - title: DOC
    content: test
baseUri: http://localhost:8080
baseUriParameters: {}
uses: 
  Domains: types.raml
  #Domains: schema.raml
#types: 
#  Domains: !include types.raml
#  UpdateDrinkByIdRequest: !include schemas/drink-put.json
#  GetDrinksResponse: !include schemas/drink-list.json
#  GetDrinkByIdResponse: !include schemas/drink-get.json
#  CreateDrinkRequest: !include schemas/drink-post.json
#  GetHealthCheckResponse: !include schemas/health-get.json
    
/drinks:
  description: url for drinks
  get:
    displayName: Drinks
    description: Retrieves a list of available drinks.
    responses:
      200:
        description: Success
        body:
          application/json:
            displayName: response
            #type: Domains.GetDrinksResponse
            type: array
            items:
              type: Domains.GetDrinksResponse
              
  post:
    displayName: Drinks
    description: Creates a new drink.
    body:
      application/json:
        displayName: body
        type: Domains.CreateDrinkRequest
        #type: !include schemas/drink-post.json
    responses:
      200:
        description: Success
        body:
          application/json:
            example:
              value:
                test: oooo
            displayName: response
            type: any
  /{drinkName}:
    description: url for get detail
    uriParameters:
      drinkName:
        required: true
        displayName: drinkName
        description: |
          The name of the drink for info

          required: true

          type: string
        type: string
    get:
      displayName: DrinksByDrinkName
      description: Retrieves details for a specific drink.
      responses:
        200:
          description: Success
          body:
            application/json:
              displayName: response
              type: Domains.GetDrinkByIdResponse
              #schema: Domains.GetDrinkByIdResponse
    put:
      displayName: DrinksByDrinkName
      description: Modify an existing drink.
      body:
        application/json:
          displayName: body
          type: Domains.UpdateDrinkByIdRequest
          #schema: Domains.UpdateDrinkByIdRequest
      responses:
        200:
          description: Success
          body:
            application/json:
              example:
                value:
                  test: oooo
              displayName: response
              type: any
    delete:
      displayName: DrinksByDrinkName
      description: Delete an existing drink.
      responses:
        200:
          description: Success
          body:
            application/json:
              example:
                value:
                  test: oooo
              displayName: response
              type: any
/healthCheck:
  description: url for health
  get:
    displayName: HealthCheck
    description: Retrieves the server's health status.
    responses:
      200:
        description: Success
        body:
          application/json:
            displayName: response
            type: Domains.GetHealthCheckResponse
            #schema: Domains.GetHealthCheckResponse
