#%RAML 1.0 Library
#usage: Use this to describe types for api
schemas:  
  UpdateDrinkByIdRequest: |
    {
      "$ref": "https://raw.githubusercontent.com/reedF/springmvc-raml-plugin-sample/master/drinks-server/src/main/resources/public/raml/schemas/drink-put.json"      
    }
  CreateDrinkRequest: | 
    {
      "$ref": "https://raw.githubusercontent.com/reedF/springmvc-raml-plugin-sample/master/drinks-server/src/main/resources/public/raml/schemas/drink-post.json"
    }
  GetDrinksResponse: |
    {
      "$ref": "https://raw.githubusercontent.com/reedF/springmvc-raml-plugin-sample/master/drinks-server/src/main/resources/public/raml/schemas/drink-list.json"
    }

  GetDrinkByIdResponse: |
    {
      "$ref": "https://raw.githubusercontent.com/reedF/springmvc-raml-plugin-sample/master/drinks-server/src/main/resources/public/raml/schemas/drink-get.json"
    }               
  GetHealthCheckResponse: |
    {
      "$ref": "https://raw.githubusercontent.com/reedF/springmvc-raml-plugin-sample/master/drinks-server/src/main/resources/public/raml/schemas/health-get.json"
    }

#types: 
#  GetDrinksResponse: !include schemas/drink-list.json
#  CreateDrinkRequest: !include schemas/drink-post.json
#  UpdateDrinkByIdRequest: !include schemas/drink-put.json
#  GetDrinkByIdResponse: !include schemas/drink-get.json
#  GetHealthCheckResponse: !include schemas/health-get.json

#schemas: 
#  CreateDrinkRequest: | 
#            {
#              "id" : "urn:jsonschema:com:phoenixnap:oss:sample:server:rest:model:CreateDrinkRequest",
#              "type": "object",
#              "properties": {
#                "type": {
#                  "type" : "object"
#                },
#                "name": {
#                  "type" : "string"
#                }
#              }              
#            }
#  GetDrinksResponse: |
#                {
#                  "id" : "urn:jsonschema:com:phoenixnap:oss:sample:server:rest:model:GetDrinksResponse",
#                  "$schema": "http://json-schema.org/draft-04/schema#",
#                  "type": "array",
#                  "items": {
#                    "$ref": "GetDrinkByIdResponse"
#                  }
#                }
#  GetDrinkByIdResponse: |
#                {
#                  "id" : "urn:jsonschema:com:phoenixnap:oss:sample:server:rest:model:GetDrinkByIdResponse",
#                  "$schema": "http://json-schema.org/draft-04/schema#",
#                  "type": "object",
#                  "properties": {
#                      "type": {
#                        "type": "string"
#                      },
#                      "name": {
#                        "type": "string"
#                      }
#                   },
#                    "required": [
#                      "type",
#                      "name"
#                    ]
#                }
#  UpdateDrinkByIdRequest: |
#              { 
#                "type": "object",
#                "properties": {                                
#                  "name": {
#                    "type" : "string"
#                  }
#                }
#              }
#  GetHealthCheckResponse: |
#      {
#         "id" : "urn:jsonschema:com:phoenixnap:oss:sample:server:rest:model:GetHealthCheckResponse", 
#         "$schema": "http://json-schema.org/draft-04/schema#",
#         "type": "object",
#         "properties": {
#            "timestamp": {
#               "type": "string"
#            },
#            "status": {
#               "type": "string"
#            }
#          },
#          "required": [
#            "timestamp",
#              "status"
#          ]
#      }   
  